### PR TITLE
Multiline show example data

### PR DESCRIPTION
**Pull request by rgieseke**
I thought it might be helpful to see the transformation of data formats in the MultiLine example by adding examples of the objects. 
Let me know if you want to include this (it does make it a bit longer to scroll before one sees the code) , then I can do the same for the SSR example and maybe look into formatting (with Highlightjs or just some improved styling).

It's the output of adding in `+page.svelte` of the example code (which I do every time I need a MultiLine plot).
```Js
$: console.log(data)
$: console.log(JSON.stringify(dataLong, null, 4));
$: console.log(flatten(dataLong, 'values'))
```  

It looks like this now:

image
image

### CODE REVIEW

**Comment by mhkeller** [comment]
Great idea. Data formats and transforms are tricker so anything to help explain them is very good. Yeah see if you can get some highlighting going on there. Thanks for this!

**Comment by mhkeller** [comment]
Great idea. Data formats and transforms are tricker so anything to help explain them is very good. Yeah see if you can get some highlighting going on there. Thanks for this!

**Comment by rgieseke** [comment]
Just made the `code` block cover full width and adjusted the SSR example as well:

image

**Comment by rgieseke** [comment]
I didn't really try to wrap my head around how the Markdown rendering and highlighting would interact as this looked good enough to me. :slightly_smiling_face:

**Pull request merged**
